/**
 * Indian districts by state ISO code (country-state-city state codes for IN).
 * Covers major districts; extend as needed. States not listed fall back to free text.
 */
export const INDIA_DISTRICTS_BY_STATE: Record<string, string[]> = {
  DL: [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi",
  ],
  MH: [
    "Mumbai City",
    "Mumbai Suburban",
    "Thane",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Sangli",
    "Satara",
    "Ahmednagar",
    "Jalgaon",
    "Nanded",
    "Amravati",
    "Chandrapur",
    "Raigad",
    "Palghar",
    "Ratnagiri",
    "Sindhudurg",
  ],
  GJ: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Bharuch",
    "Kheda",
    "Mehsana",
    "Patan",
    "Sabarkantha",
    "Banaskantha",
    "Kutch",
    "Morbi",
    "Surendranagar",
    "Amreli",
    "Navsari",
  ],
  KA: [
    "Bengaluru Urban",
    "Bengaluru Rural",
    "Mysuru",
    "Mangaluru",
    "Belagavi",
    "Hubballi-Dharwad",
    "Kalaburagi",
    "Ballari",
    "Tumakuru",
    "Davanagere",
    "Shivamogga",
    "Udupi",
    "Hassan",
    "Mandya",
    "Raichur",
    "Bidar",
    "Kodagu",
    "Chikkamagaluru",
    "Ramanagara",
    "Chitradurga",
  ],
  TN: [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Tiruppur",
    "Kanchipuram",
    "Cuddalore",
    "Kanyakumari",
    "Nilgiris",
    "Namakkal",
    "Karur",
    "Sivaganga",
    "Virudhunagar",
  ],
  UP: [
    "Lucknow",
    "Kanpur Nagar",
    "Varanasi",
    "Agra",
    "Prayagraj",
    "Ghaziabad",
    "Noida",
    "Meerut",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Ayodhya",
    "Mathura",
    "Jhansi",
    "Rampur",
    "Shahjahanpur",
    "Muzaffarnagar",
    "Etawah",
  ],
  RJ: [
    "Jaipur",
    "Jodhpur",
    "Udaipur",
    "Kota",
    "Ajmer",
    "Bikaner",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Jaisalmer",
    "Churu",
    "Hanumangarh",
    "Sri Ganganagar",
    "Barmer",
    "Nagaur",
    "Jhalawar",
    "Dungarpur",
    "Banswara",
    "Chittorgarh",
  ],
  WB: [
    "Kolkata",
    "North 24 Parganas",
    "South 24 Parganas",
    "Howrah",
    "Hooghly",
    "Paschim Bardhaman",
    "Purba Bardhaman",
    "Murshidabad",
    "Nadia",
    "Malda",
    "Darjeeling",
    "Jalpaiguri",
    "Siliguri",
    "Bankura",
    "Purulia",
    "Medinipur",
    "Jhargram",
    "Alipurduar",
    "Cooch Behar",
    "Dinajpur",
  ],
  BR: [
    "Patna",
    "Gaya",
    "Muzaffarpur",
    "Bhagalpur",
    "Darbhanga",
    "Purnia",
    "Begusarai",
    "Katihar",
    "Sitamarhi",
    "Samastipur",
    "Vaishali",
    "Saran",
    "Siwan",
    "Chapra",
    "Motihari",
    "Bettiah",
    "Ara",
    "Buxar",
    "Jehanabad",
    "Nalanda",
  ],
  TG: [
    "Hyderabad",
    "Rangareddy",
    "Medchal",
    "Sangareddy",
    "Nizamabad",
    "Karimnagar",
    "Warangal Urban",
    "Khammam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Jagtial",
    "Peddapalli",
    "Siddipet",
    "Vikarabad",
    "Mancherial",
    "Bhadradri Kothagudem",
    "Jayashankar Bhupalpally",
    "Mulugu",
    "Narayanpet",
  ],
  AP: [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Anantapur",
    "Kadapa",
    "Chittoor",
    "Srikakulam",
    "Vizianagaram",
    "East Godavari",
    "West Godavari",
    "Krishna",
    "Prakasam",
    "Tirupati",
    "Annamayya",
    "Alluri Sitharama Raju",
    "Parvathipuram Manyam",
    "NTR",
    "Palnadu",
  ],
  PB: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Gurdaspur",
    "Hoshiarpur",
    "Moga",
    "Firozpur",
    "Sangrur",
    "Mansa",
    "Barnala",
    "Fazilka",
    "Pathankot",
    "Tarn Taran",
    "Kapurthala",
    "Rupnagar",
    "SAS Nagar",
    "Faridkot",
  ],
  HR: [
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Hisar",
    "Karnal",
    "Rohtak",
    "Sonipat",
    "Yamunanagar",
    "Sirsa",
    "Rewari",
    "Jind",
    "Bhiwani",
    "Kurukshetra",
    "Panchkula",
    "Palwal",
    "Jhajjar",
    "Nuh",
    "Charkhi Dadri",
    "Kaithal",
  ],
};

export function getIndiaDistrictsForState(stateIsoCode: string): string[] {
  const list = INDIA_DISTRICTS_BY_STATE[stateIsoCode];
  return list ? [...list].sort((a, b) => a.localeCompare(b)) : [];
}
